# Generated by Django 5.1 on 2024-08-25 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_event_public_date_alter_event_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='Images',
            field=models.ImageField(default='', upload_to='Voy'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='Type',
            field=models.CharField(choices=[('Event of the season', 'Event of the season'), ('Travel Organize', 'Travel Organize'), ('Business event', 'Business Event'), ('Event', 'Event'), ('Tour Organize', 'Tour Organize')], max_length=100),
        ),
    ]
