# Generated by Django 5.1 on 2024-08-25 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_category_event_images_alter_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='Category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='event.category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='Type',
            field=models.CharField(choices=[('Travel Organize', 'Travel Organize'), ('Tour Organize', 'Tour Organize'), ('Event of the season', 'Event of the season'), ('Event', 'Event'), ('Business event', 'Business Event')], max_length=100),
        ),
    ]
