# Generated by Django 5.1 on 2024-08-25 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_event_category_alter_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='Type',
            field=models.CharField(choices=[('Event of the season', 'Event of the season'), ('Travel Organize', 'Travel Organize'), ('Tour Organize', 'Tour Organize'), ('Business event', 'Business Event'), ('Event', 'Event')], max_length=100),
        ),
    ]
