# Generated by Django 5.1 on 2024-08-28 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_alter_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='Images',
            field=models.ImageField(upload_to='events/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='Type',
            field=models.CharField(choices=[('Tour Organize', 'Tour Organize'), ('Business event', 'Business Event'), ('Event', 'Event'), ('Event of the season', 'Event of the season'), ('Travel Organize', 'Travel Organize')], max_length=100),
        ),
    ]
