# Generated by Django 5.1 on 2024-09-01 20:38

import event.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0010_alter_event_images_alter_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='event_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='Images',
            field=models.ImageField(blank=True, null=True, upload_to=event.models.image_upload),
        ),
        migrations.AlterField(
            model_name='event',
            name='Type',
            field=models.CharField(choices=[('Travel Organize', 'Travel Organize'), ('Event', 'Event'), ('Tour Organize', 'Tour Organize'), ('Business event', 'Business Event'), ('Event of the season', 'Event of the season')], max_length=100),
        ),
    ]
