# Generated by Django 5.1 on 2024-09-03 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0016_alter_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='Type',
            field=models.CharField(choices=[('Event of the season', 'Event of the season'), ('Business event', 'Business Event'), ('Event', 'Event'), ('Travel Organize', 'Travel Organize'), ('Tour Organize', 'Tour Organize')], max_length=100),
        ),
    ]
