# Generated by Django 5.1 on 2024-09-03 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0017_alter_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='Type',
            field=models.CharField(choices=[('Event of the season', 'Event of the season'), ('Travel Organize', 'Travel Organize'), ('Tour Organize', 'Tour Organize'), ('Business event', 'Business Event'), ('Event', 'Event')], max_length=100),
        ),
    ]
