# Generated by Django 5.1 on 2024-09-04 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0018_event_slug_alter_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='Type',
            field=models.CharField(choices=[('Travel Organize', 'Travel Organize'), ('Tour Organize', 'Tour Organize'), ('Business event', 'Business Event'), ('Event of the season', 'Event of the season'), ('Event', 'Event')], max_length=100),
        ),
    ]
