# Generated by Django 5.1 on 2024-09-06 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0019_alter_event_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='event_date',
        ),
        migrations.AddField(
            model_name='event',
            name='event_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='Groupe_size',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='Include',
            field=models.TextField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='Nbr_jours',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='Pays',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='Public_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='Type',
            field=models.CharField(choices=[('Tour Organize', 'Tour Organize'), ('Business event', 'Business Event'), ('Event', 'Event'), ('Travel Organize', 'Travel Organize'), ('Event of the season', 'Event of the season')], max_length=100),
        ),
    ]
