# Generated by Django 4.2.16 on 2024-09-11 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0020_remove_category_event_date_event_event_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='Type',
            field=models.CharField(choices=[('Business event', 'Business Event'), ('Event of the season', 'Event of the season'), ('Travel Organize', 'Travel Organize'), ('Tour Organize', 'Tour Organize'), ('Event', 'Event')], max_length=100),
        ),
    ]
