# Generated by Django 4.2.16 on 2024-09-13 23:06

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0022_alter_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='Localisation',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='Type',
            field=models.CharField(choices=[('Business event', 'Business Event'), ('Event of the season', 'Event of the season'), ('Tour Organize', 'Tour Organize'), ('Event', 'Event'), ('Travel Organize', 'Travel Organize')], max_length=100),
        ),
    ]
