# Generated by Django 4.2.16 on 2024-09-13 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0023_alter_event_localisation_alter_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='Type',
            field=models.CharField(choices=[('Event', 'Event'), ('Travel Organize', 'Travel Organize'), ('Tour Organize', 'Tour Organize'), ('Event of the season', 'Event of the season'), ('Business event', 'Business Event')], max_length=100),
        ),
    ]
