# Generated by Django 4.2.16 on 2024-09-13 23:51

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0024_alter_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='Description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='Localisation',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='Type',
            field=models.CharField(choices=[('Travel Organize', 'Travel Organize'), ('Tour Organize', 'Tour Organize'), ('Event of the season', 'Event of the season'), ('Event', 'Event'), ('Business event', 'Business Event')], max_length=100),
        ),
    ]
