# Generated by Django 4.2.16 on 2024-09-13 23:54

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0026_alter_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='Description',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='Type',
            field=models.CharField(choices=[('Travel Organize', 'Travel Organize'), ('Tour Organize', 'Tour Organize'), ('Business event', 'Business Event'), ('Event of the season', 'Event of the season'), ('Event', 'Event')], max_length=100),
        ),
    ]
