# Generated by Django 4.2.16 on 2024-09-14 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0027_alter_event_description_alter_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='Type',
            field=models.CharField(choices=[('Travel Organize', 'Travel Organize'), ('Business event', 'Business Event'), ('Tour Organize', 'Tour Organize'), ('Event', 'Event'), ('Event of the season', 'Event of the season')], max_length=100),
        ),
    ]
