# Generated by Django 4.2.16 on 2024-09-21 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0028_alter_event_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=50)),
                ('destination', models.CharField(max_length=200)),
                ('number_of_people', models.IntegerField()),
                ('special_requests', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='Type',
            field=models.CharField(choices=[('Event of the season', 'Event of the season'), ('Event', 'Event'), ('Business event', 'Business Event'), ('Tour Organize', 'Tour Organize'), ('Travel Organize', 'Travel Organize')], max_length=100),
        ),
    ]
