# Generated by Django 4.2.16 on 2024-09-21 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0029_apply_alter_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='apply_event', to='event.event'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='Type',
            field=models.CharField(choices=[('Event of the season', 'Event of the season'), ('Tour Organize', 'Tour Organize'), ('Travel Organize', 'Travel Organize'), ('Business event', 'Business Event'), ('Event', 'Event')], max_length=100),
        ),
    ]
