# Generated by Django 4.2.16 on 2024-09-21 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0030_apply_event_alter_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='Type',
            field=models.CharField(choices=[('Travel Organize', 'Travel Organize'), ('Event', 'Event'), ('Event of the season', 'Event of the season'), ('Tour Organize', 'Tour Organize'), ('Business event', 'Business Event')], max_length=100),
        ),
    ]
