# Generated by Django 4.2.16 on 2024-09-21 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0032_alter_event_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apply',
            old_name='destination',
            new_name='pay',
        ),
        migrations.AddField(
            model_name='apply',
            name='id_passport',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='Type',
            field=models.CharField(choices=[('Event', 'Event'), ('Tour Organize', 'Tour Organize'), ('Event of the season', 'Event of the season'), ('Travel Organize', 'Travel Organize'), ('Business event', 'Business Event')], max_length=100),
        ),
    ]
