# Generated by Django 4.2.16 on 2024-09-21 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0033_rename_destination_apply_pay_apply_id_passport_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='number_of_people',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='Type',
            field=models.CharField(choices=[('Tour Organize', 'Tour Organize'), ('Event', 'Event'), ('Business event', 'Business Event'), ('Event of the season', 'Event of the season'), ('Travel Organize', 'Travel Organize')], max_length=100),
        ),
    ]
