# Generated by Django 4.2.16 on 2024-09-21 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0034_alter_apply_number_of_people_alter_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='Type',
            field=models.CharField(choices=[('Tour Organize', 'Tour Organize'), ('Event', 'Event'), ('Business event', 'Business Event'), ('Travel Organize', 'Travel Organize'), ('Event of the season', 'Event of the season')], max_length=100),
        ),
    ]
