# Generated by Django 4.2.16 on 2024-09-21 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0035_alter_event_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apply',
            old_name='pay',
            new_name='nationality',
        ),
        migrations.AlterField(
            model_name='event',
            name='Type',
            field=models.CharField(choices=[('Tour Organize', 'Tour Organize'), ('Travel Organize', 'Travel Organize'), ('Event of the season', 'Event of the season'), ('Event', 'Event'), ('Business event', 'Business Event')], max_length=100),
        ),
    ]
