# Generated by Django 4.2.16 on 2024-09-22 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0036_rename_pay_apply_nationality_alter_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='Type',
            field=models.CharField(choices=[('Event of the season', 'Event of the season'), ('Business event', 'Business Event'), ('Travel Organize', 'Travel Organize'), ('Event', 'Event'), ('Tour Organize', 'Tour Organize')], max_length=100),
        ),
    ]
