# Generated by Django 4.2.16 on 2024-09-22 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0037_alter_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='number_of_people',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='event',
            name='Type',
            field=models.CharField(choices=[('Business event', 'Business Event'), ('Travel Organize', 'Travel Organize'), ('Event', 'Event'), ('Tour Organize', 'Tour Organize'), ('Event of the season', 'Event of the season')], max_length=100),
        ),
    ]
