# Generated by Django 4.2.16 on 2024-09-24 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0038_alter_apply_number_of_people_alter_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='Type',
            field=models.CharField(choices=[('Business event', 'Business Event'), ('Travel Organize', 'Travel Organize'), ('Event of the season', 'Event of the season'), ('Event', 'Event'), ('Tour Organize', 'Tour Organize')], max_length=100),
        ),
    ]
